name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#example-6
      - name: Upload app and set app location
        run: |
          APP_UPLOAD_RESPONSE=$(curl -u "BROWSERSTACK_USERNAME:BROWSERSTACK_ACCESS_KEY" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "url=https://github.com/dipjyotimetia/GIT_LFS/raw/master/com.booking_2020-12-16.apk")
          echo "APP_URL=$(echo $APP_UPLOAD_RESPONSE | jq -r '.app_url')" >> $GITHUB_ENV
      - name: Gradle Run Test
        run: ./gradlew task e2e
      - name: Generate Report
        run: ./gradlew task allureReport
      - uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: build/reports/allure-report
      - uses: actions/upload-artifact@v2
        with:
          name: extent-report
          path: Reports
